// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SquareOfOpposition.Web.Data;

#nullable disable

namespace SquareOfOpposition.Web.Migrations
{
    [DbContext(typeof(SquareOfOppositionDbContext))]
    partial class SquareOfOppositionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SquareOfOpposition.Web.Models.Domain.Square", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenranceO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SentanceA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SentanceE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SentanceI")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Squares");
                });
#pragma warning restore 612, 618
        }
    }
}
